### ISSUE TITLE
Blender addon error when setting up collisions in a particular order

### ISSUE THREAD

**Issue by Lamoot** [bikemurt/blender-godot-pipeline#4]
Here's another error popup bug. It occurs when custom properties are added in a particular order, starting with _Set Collisions_

Steps to reproduce:
1. Set Collisions
2. Set a path, here using _material_0_
3. Set Collisions again, a common action, when a user wants to edit and update the collisions 

![error_with_property_order](https://github.com/user-attachments/assets/02e1c784-82f5-4b25-b33f-79c9480a2505)

- The bug doesn't happen if a path was set before collisions were set.
- The bug happens if a custom property, not related to the addon, is added manually.
- _Set Collisions_ still works as intended, the collision type is changed and values are properly updated. The error doesn't block the functionality at all.
- The bug stops appearing when collision is set to one of the types with a single property  (mesh, simple, none).

Blender 4.2.3 and 2.4 version of the Blender addon.

**Comment by bikemurt** [comment]
This issue has been patched. The fix is to forcibly delete the collision field before setting the collision properties. This works because we overwrite the object's `collision` custom property every time prior to setting the collision shape details.

See version 2.4.2 files on Blender Market: https://blendermarket.com/products/blender-godot-pipeline-addon

I will leave the issue open for a bit to allow for some re-testing
