### ISSUE TITLE
Proposal: Instantiate arbitrary nodes

### ISSUE THREAD

**Issue by joeymanderley** [bikemurt/blender-godot-pipeline#8]
Great addon! I've been playing with it and I have a feature suggestion that potentially adds powerful new functionality if you think it's a good fit for the scope of the project (and you have the time or desire to implement it).

Conceptually, what the "Collisions" section effectively does is it allows the user to select which type of PhysicsBody3D-derived node to spawn + which type of Shape3D child node to automatically generate from geometry. An obvious candidate for future updates is to expand beyond just PhysicsBody3D-derived nodes (OccluderInstance3Ds + Occluder3D, Path3D etc.)

But most Godot nodes don't need geometry or sub-nodes at all, just a transform, so why not have an option where the user can select 'Custom Node' for 'Body' and it lets them type in the name of any* built-in** class to spawn (via something like 'ClassDB.instantiate')?

* The importer should probably throw an error if the class isn't a Node3D subclass to avoid breaking 3D parent-child hierarchies
** The path setter functionality already lets the user spawn custom Node3D classes by setting a script.

**Comment by bikemurt** [comment]
Interesting idea. One caveat is that I would be able to allow any Godot class to be selected from the "Custom Node" dropdown - it would need to be a curated list of classes that would have well-defined behaviour. For instance, one of the options could be "Occluder", enabling the following workflow:

1. Use a default cube (or any mesh) in Blender, set position and size
2. Set "Custom Node" as the Body type (or maybe just "None"), then select "Occluder" from a dropdown
3. Hit "Set Collisions"
4. On Godot side, there is a custom import instruction for an "Occluder" physics body that generates an OccluderInstance3D, as well as the Occluder3D tied to it. If a Box collision was chosen, then the Occluder3D will be a BoxOccluder3D

I agree that it would be powerful - basically leveraging the geometry calculations from the Blender addon. My concern is that it would clutter the collisions interface. Path3D would diverge from how the collision shapes function. And I suspect more of these custom nodes would as well.

So I'm thinking the best interface would be to add a checkbox at the bottom of the Collisions box, which is normally unchecked, but when selected, it provides options to generate these custom nodes. I might call it "Override Node" rather than custom, just to be clear that it's still limited in scope. I think on the Godot side it would have to be limited to a few of these nodes to start, see how the additional functionality works.

![image](https://github.com/user-attachments/assets/67b92225-0962-489d-9007-81d4d03ada9d)

![image](https://github.com/user-attachments/assets/cd0b3be2-3da0-4419-afd3-21b2e595380e)

![image](https://github.com/user-attachments/assets/26fdb098-3fa0-4293-b523-fc13b2bf65af)

Under the hood, the Set Node" button would be a new Blender operator, but it can still use the underlying operator for setting collision shapes.

Let me know what you think.

**Comment by joeymanderley** [comment]
Well the conception in my head (which I didn't include in my suggestion because it might be a bigger refactor than you would want for what you're trying to do with your addon) was that the "Collisions" selection eventually becomes more of a generalized "Target Node" selection. Since Occluder and Physics Body don't usually need them to be on the same object, they could occupy the same mutually excluding control.

So instead of a "Collision" dropdown and a "Body" dropdown, there would be an initial "Body" dropdown, which would actually become a "what node do you want to make on import?" dropdown, and it would include the physics bodies (static, rigid, area, etc.), Occluder, None (default Node3D), and Custom (type your own). 
Then when the user selects what they want from this dropdown, the GUI under the control shows further options as applicable: 
* Selecting one of the physics bodies presents the Collision dropdown as before, Collision Margin, Apply Scale, etc.
* Selecting occluder presents occluder-specific collision types (which aren't the same as physics body collision types; there's no cylinder, for example) and so on. 

This opens up the possibility of supporting other types of nodes that contain spatial but non-mesh data (such as Path3D) without having to find a place for it in a separate UI panel. You'd just add Path3D to the "Body" dropdown and selecting it would show Path3D specific settings.

But that was my initial *first draft* idea. You could also--and it would probably be easier to--just make a separate UI panel similar to "Path Setter", "String Setter", etc. for non-collision "Custom Node"s.

The "type your own custom node class" idea serves as a catch-all for situations where the user doesn't need geometry but wants to define the 3D position and orientation of something in Blender and have it carry over into Godot (which they can already do with a "None" body for plain Node3Ds) but this would additionally allow a stopgap way of specifying simple camera or light setups in Blender without having to wait for explicit pipeline support.

**But ultimately it comes down to what you think is best and have time for** (I personally don't actually need any of this functionality right now; it just popped into my head while messing around and thinking about what kinds of other data Blender generates that could be brought into Godot). UX design is *definitely* not my forte, and I think just having the feature somewhere adds value no matter where it is.

**Comment by joeymanderley** [comment]
So I went ahead and started on a custom addon (for my own internal use), mostly to coalesce this idea and some other related ideas, but also to get familiar with the Blender API for something else I need to write in the future.

But here's how the UI *could* look as I was originally envisioning it (ignore the other stuff):

You'd have a node override panel with a dropdown:
![1](https://github.com/user-attachments/assets/7e2427d8-81b3-402f-8bec-396e5f0484d0)

![2](https://github.com/user-attachments/assets/1426e2ea-31d0-49f4-b57f-090a2d2ca720)

Settings appropriate to the current dropdown are shown when selection changes:
![3](https://github.com/user-attachments/assets/4b4830ee-a4d8-4058-9132-947673986e56)

![4](https://github.com/user-attachments/assets/11604d5d-6692-4040-bdcb-ce02e65ec34a)

**Comment by bikemurt** [comment]
That's awesome, I love to see when people are able to build out their own tooling. I will close this issue as these features won't really be in scope, unless I can really justify the added complexity. The branch still exists, so if you find something else interesting feel free to respond to the closed issue (just @ me) and I might consider adding some stuff to the main addon.
